using System.Collections.ObjectModel;
using System.ComponentModel;
using Lecin.Models;
using Lecin.Services;
using System.Net.Http.Json;
using Microsoft.Maui.Controls;

namespace Lecin.Pages;


public partial class TeacherAttendancePage : ContentPage
{
    private readonly HttpClient _http = new();
    const string BaseUrl = "http://localhost:5105";

    public TeacherAttendancePage()
    {
        InitializeComponent();  // <-- will be generated by the XAML compiler once hooked up
    }

    private async void OnGetAttendanceClicked(object sender, EventArgs e)
    {
        ErrorLabel.IsVisible = false;
        OverallLabel.Text = "";

        if (!Guid.TryParse(StudentIdEntry.Text, out var studentId))
        {
            ErrorLabel.Text = "Enter a valid GUID for Student ID.";
            ErrorLabel.IsVisible = true;
            return;
        }

        try
        {
            var url = $"{BaseUrl}/api/teacher/attendance/percentage/{studentId}";
            var dto = await _http.GetFromJsonAsync<AttendancePercentageDto>(
                url,
                new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            if (dto is null)
            {
                ErrorLabel.Text = "No data.";
                ErrorLabel.IsVisible = true;
                return;
            }

            OverallLabel.Text = $"Overall: {dto.Percentage:F1}% ({dto.Attended}/{dto.TotalClasses})";
        }
        catch (Exception ex)
        {
            ErrorLabel.Text = ex.Message;
            ErrorLabel.IsVisible = true;
        }
    }

    // Frontend shape; keep in sync with your backend response
    public record AttendancePercentageDto(
        Guid StudentId,
        int TotalClasses,
        int Attended,
        double Percentage,
        List<CourseAttendanceDto> ByCourse
    );
    public record CourseAttendanceDto(string CourseCode, int TotalClasses, int Attended, double Percentage);
}



/*
public partial class TeacherAttendancePage : ContentPage
{
    private readonly VM vm = new();
    public TeacherAttendancePage()
    {
        InitializeComponent();          // generated when x:Class matches this namespace/class
        BindingContext = vm;
    }

    private async void OnFetchClicked(object? sender, EventArgs e)
    {
        vm.Clear();
        if (!Guid.TryParse(StudentIdEntry.Text?.Trim(), out var studentId))
        {
            vm.Message = "Please enter a valid GUID.";
            return;
        }

        try
        {
            var dto = await BackendClient.GetStudentAttendancePercentAsync(studentId);
            if (dto.TotalClasses == 0)
            {
                vm.Message = "No classes/enrollments found for that student.";
                return;
            }

            vm.OverallText = $"{dto.Attended}/{dto.TotalClasses} classes • {dto.Percentage:F1}%";
            foreach (var c in dto.ByCourse)
                vm.Courses.Add(new CourseRow(c.CourseCode, c.Attended, c.TotalClasses, c.Percentage));
        }
        catch (Exception ex)
        {
            vm.Message = $"Error: {ex.Message}";
        }
    }

    class VM : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        void N(string p) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(p));

        public ObservableCollection<CourseRow> Courses { get; } = new();
        string overall = ""; public string OverallText { get => overall; set { overall = value; N(nameof(OverallText)); N(nameof(HasData)); } }
        string message = ""; public string Message { get => message; set { message = value; N(nameof(Message)); N(nameof(HasMessage)); } }
        public bool HasData => Courses.Count > 0 || !string.IsNullOrWhiteSpace(OverallText);
        public bool HasMessage => !string.IsNullOrWhiteSpace(Message);
        public void Clear() { Courses.Clear(); OverallText = ""; Message = ""; }
    } 



    public record CourseRow(string CourseCode, int Attended, int Total, double Percentage)
    {
        public string TotalsLine => $"{Attended}/{Total} • {Percentage:F1}%";
    }
}

*/