name: Build and Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install EMGU CV dependencies
        run: sudo apt install mono-complete build-essential libgtk-3-dev libgstreamer1.0-dev libavcodec-dev libswscale-dev libavformat-dev libdc1394-dev libv4l-dev cmake-curses-gui ocl-icd-dev freeglut3-dev libgeotiff-dev libusb-1.0-0-dev libvtk9-dev libfreetype-dev libharfbuzz-dev qtbase5-dev libeigen3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgflags-dev libgoogle-glog-dev liblapacke-dev libva-dev dotnet-sdk-8.0
        
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: '2.40.7'
          
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Start Supabase local development
        run: supabase start
          
      - name: Setup Deno Imports
        working-directory: "./supabase/functions"
        run: deno install
        
      - name: Run deno unit tests
        working-directory: "./supabase/functions"
        run: deno test --allow-all
          
      # Restore, build, and test the .NET project

      - name: Restore workloads
        working-directory: "./src"
        run: dotnet workload restore
        
      - name: Restore dependencies
        working-directory: "./src"
        run: dotnet restore

      - name: Build
        working-directory: "./src"
        run: dotnet build --no-restore
      - name: Test
        working-directory: "./src"
        run: dotnet test --no-build --verbosity normal